version: '3.8'

services:
  server:
    container_name: todo_server
    build: .
    depends_on:
      - postgres
    ports:
      - '8000:8000'
    volumes:
      - .:/usr/app
    env_file: .env
    command: python manage.py runserver 0.0.0.0:8000

  postgres:
    container_name: todo_postgres
    image: postgres
    environment: 
      POSTGRES_DB: todo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
